"""Candidate companies to probe — only entries that pass live API tests are kept."""

# (display_name, board_slug)
GREENHOUSE_CANDIDATES = [
    ("1Password", "1password"), ("1Password", "agilebits"),
    ("Acronis", "acronis"), ("ActiveCampaign", "activecampaign"),
    ("Adyen", "adyen"), ("Agoda", "agoda"), ("Airtable", "airtable"),
    ("Alchemy", "alchemy"), ("Alation", "alation"), ("AlertMedia", "alertmedia"),
    ("Alluxio", "alluxio"), ("Alpaca", "alpaca"), ("Amplitude", "amplitude"),
    ("Anduril", "andurilindustries"), ("Anthropic", "anthropic"),
    ("Apollo.io", "apolloio"), ("AppLovin", "applovin"), ("Asana", "asana"),
    ("Astranis", "astranis"), ("Attentive", "attentive"), ("Automattic", "automattic"),
    ("Axon", "axon"), ("Benchling", "benchling"), ("BetterHelp", "betterhelp"),
    ("BitGo", "bitgo"), ("BlackSky", "blacksky"), ("Bloomreach", "bloomreach"),
    ("BlueVine", "bluevine"), ("Bolt", "bolt"), ("Boomi", "boomi"),
    ("Box", "box"), ("Box", "boxinc"), ("Branch", "branch"),
    ("Brex", "brex"), ("Calendly", "calendly"), ("Carta", "carta"),
    ("Checkr", "checkr"), ("Chime", "chime"), ("Circle", "circle"),
    ("Clear", "clear"), ("Cloudflare", "cloudflare"), ("Coinbase", "coinbase"),
    ("Confluent", "confluent"), ("Contentful", "contentful"),
    ("Coursera", "coursera"), ("CrowdStrike", "crowdstrike"),
    ("Databricks", "databricks"), ("Datadog", "datadog"),
    ("Discord", "discord"), ("DoorDash", "doordash"), ("DoorDash", "doordashusa"),
    ("Dropbox", "dropbox"), ("Duolingo", "duolingo"), ("Elastic", "elastic"),
    ("Epic Games", "epicgames"), ("Faire", "faire"), ("Faire", "fairewholesale"),
    ("Fastly", "fastly"), ("Figma", "figma"), ("Fivetran", "fivetran"),
    ("Flexport", "flexport"), ("Glean", "glean"), ("Glean", "gleanwork"),
    ("GitLab", "gitlab"), ("Gong", "gong"), ("Gong", "gongio"),
    ("Grafana Labs", "grafanalabs"), ("Gusto", "gusto"),
    ("HashiCorp", "hashicorp"), ("HubSpot", "hubspot"),
    ("Hinge", "hinge"), ("Instacart", "instacart"), ("Intercom", "intercom"),
    ("JFrog", "jfrog"), ("Klaviyo", "klaviyo"), ("LaunchDarkly", "launchdarkly"),
    ("Linear", "linear"), ("Lucid Motors", "lucidmotors"), ("Lyft", "lyft"),
    ("Marqeta", "marqeta"), ("Mercury", "mercury"), ("Mixpanel", "mixpanel"),
    ("MongoDB", "mongodb"), ("Navan", "tripactions"), ("New Relic", "newrelic"),
    ("Notion", "notion"), ("Nubank", "nubank"), ("Okta", "okta"),
    ("Opendoor", "opendoor"), ("PagerDuty", "pagerduty"),
    ("Palantir", "palantir"), ("Pinterest", "pinterest"),
    ("Plaid", "plaid"), ("Postman", "postman"), ("Procore", "procore"),
    ("Ramp", "ramp"), ("Ramp", "rampnetwork"), ("Reddit", "reddit"),
    ("Remote", "remotecom"), ("Rippling", "rippling"), ("Roblox", "roblox"),
    ("Roku", "roku"), ("Rubrik", "rubrik"), ("Samsara", "samsara"),
    ("Scale AI", "scaleai"), ("SentinelOne", "sentinelone"),
    ("Shopify", "shopify"), ("Smartsheet", "smartsheet"), ("Snap", "snap"),
    ("Snap", "snapchat"), ("Snowflake", "snowflake"), ("SoFi", "sofi"),
    ("Sourcegraph", "sourcegraph"), ("Sourcegraph", "sourcegraph91"),
    ("SpaceX", "spacex"), ("Squarespace", "squarespace"),
    ("Stripe", "stripe"), ("Tailscale", "tailscale"), ("Toast", "toast"),
    ("Twilio", "twilio"), ("Uber", "uber"), ("Unity", "unity"),
    ("Unity", "unity3d"), ("Vercel", "vercel"), ("Verkada", "verkada"),
    ("Waymo", "waymo"), ("Webflow", "webflow"), ("Wiz", "wizinc"),
    ("Zscaler", "zscaler"), ("dbt Labs", "dbtlabsinc"),
    ("Affirm", "affirm"), ("Airbnb", "airbnb"), ("Aurora", "aurorainnovation"),
    ("Block", "block"), ("Braze", "braze"), ("Deel", "deel"),
    ("Riot Games", "riotgames"), ("Robinhood", "robinhood"),
    ("Stability AI", "stabilityai"), ("Zillow", "zillow"),
    ("Acorns", "acorns"), ("Addepar", "addepar"), ("Airbyte", "airbyte"),
    ("Airtable", "airtable"), ("Algolia", "algolia"), ("Allbirds", "allbirds"),
    ("Anchorage", "anchorage"), ("Andela", "andela"), ("Anaplan", "anaplan"),
    ("Angi", "angi"), ("Ansys", "ansys"), ("Anyscale", "anyscale"),
    ("AppDynamics", "appdynamics"), ("AppFolio", "appfolio"), ("Appian", "appian"),
    ("Argo AI", "argoai"), ("Asana", "asana"), ("Aspire", "aspire"),
    ("Atlassian", "atlassian"), ("Attentive", "attentive"), ("AuditBoard", "auditboard"),
    ("Automox", "automox"), ("Ava Labs", "avalabs"), ("Axonius", "axonius"),
    ("BambooHR", "bamboohr"), ("Baseten", "baseten"), ("Benchling", "benchling"),
    ("BetterUp", "betterup"), ("BigID", "bigid"), ("Bill.com", "billcom"),
    ("Bird", "bird"), ("Bitwarden", "bitwarden"), ("Blend", "blend"),
    ("Blockdaemon", "blockdaemon"), ("Bluecore", "bluecore"), ("Braze", "braze"),
    ("Bright Machines", "brightmachines"), ("Bumble", "bumble"),
    ("Cadence", "cadence"), ("Calm", "calm"), ("Canva", "canva"),
    ("Capillary", "capillarytech"), ("Carbon Health", "carbonhealth"),
    ("CarGurus", "cargurus"), ("Carvana", "carvana"), ("Celonis", "celonis"),
    ("Chainalysis", "chainalysis"), ("Chainguard", "chainguard"),
    ("Chargebee", "chargebee"), ("Checkr", "checkr"), ("Chronosphere", "chronosphere"),
    ("CircleCI", "circleci"), ("Clari", "clari"), ("Clearbit", "clearbit"),
    ("ClickUp", "clickup"), ("Cloudflare", "cloudflare"), ("Cloudinary", "cloudinary"),
    ("Cockroach Labs", "cockroachlabs"), ("Cohere", "cohere"),
    ("Collibra", "collibra"), ("Color", "color"), ("Commure", "commure"),
    ("Confluent", "confluent"), ("Convoy", "convoy"), ("Copper", "copper"),
    ("CoreWeave", "coreweave"), ("Couchbase", "couchbase"), ("Coursera", "coursera"),
    ("Cruise", "getcruise"), ("Crusoe", "crusoe"), ("Cruise", "cruise"),
    ("CyberArk", "cyberark"), ("Dandy", "dandy"), ("Dashlane", "dashlane"),
    ("Dataiku", "dataiku"), ("DataRobot", "datarobot"), ("Deel", "deel"),
    ("Deliveroo", "deliveroo"), ("Dialpad", "dialpad"), ("Discord", "discord"),
    ("Docker", "docker"), ("DocuSign", "docusign"), ("Domo", "domo"),
    ("DoorDash", "doordashusa"), ("Drata", "drata"), ("Dropbox", "dropbox"),
    ("Druva", "druva"), ("Duolingo", "duolingo"), ("Dynatrace", "dynatrace"),
    ("EarnIn", "earnin"), ("Elastic", "elastic"), ("Employment Hero", "employmenthero"),
    ("Enfusion", "enfusion"), ("Envoy", "envoy"), ("Epic Games", "epicgames"),
    ("Equinix", "equinix"), ("Etsy", "etsy"), ("Eventbrite", "eventbrite"),
    ("Everlaw", "everlaw"), ("Exabeam", "exabeam"), ("Expedia", "expedia"),
    ("Extend", "extend"), ("Faire", "faire"), ("Fanatics", "fanatics"),
    ("Farfetch", "farfetch"), ("Fivetran", "fivetran"), ("Flexport", "flexport"),
    ("Flipkart", "flipkart"), ("FloQast", "floqast"), ("FlutterFlow", "flutterflow"),
    ("Formlabs", "formlabs"), ("Fortinet", "fortinet"), ("Freshworks", "freshworks"),
    ("Front", "front"), ("FullStory", "fullstory"), ("Gainsight", "gainsight"),
    ("Gem", "gem"), ("Genesys", "genesys"), ("GitHub", "github"),
    ("GitLab", "gitlab"), ("Glean", "gleanwork"), ("GoFundMe", "gofundme"),
    ("Gong", "gongio"), ("Grammarly", "grammarly"), ("Greenhouse", "greenhouse"),
    ("Gusto", "gusto"), ("HackerOne", "hackerone"), ("Harness", "harness"),
    ("HashiCorp", "hashicorp"), ("Hinge", "hinge"), ("Hopper", "hopper"),
    ("HubSpot", "hubspot"), ("Hugging Face", "huggingface"), ("Human Interest", "humaninterest"),
    ("Immuta", "immuta"), ("Impossible Foods", "impossiblefoods"),
    ("Inflection", "inflection"), ("Instacart", "instacart"), ("Instabase", "instabase"),
    ("Intercom", "intercom"), ("Intuit", "intuit"), ("Invoca", "invoca"),
    ("Ironclad", "ironclad"), ("Iterable", "iterable"), ("Ivanti", "ivanti"),
    ("Jamf", "jamf"), ("Jasper", "jasper"), ("JFrog", "jfrog"),
    ("Justworks", "justworks"), ("Kajabi", "kajabi"), ("Klaviyo", "klaviyo"),
    ("Klarna", "klarna"), ("Kong", "kong"), ("Kraken", "kraken"),
    ("Lacework", "lacework"), ("Lambda", "lambda"), ("Lattice", "lattice"),
    ("LaunchDarkly", "launchdarkly"), ("LeanData", "leandata"), ("Lemonade", "lemonade"),
    ("Lime", "lime"), ("Linear", "linear"), ("Loom", "loom"),
    ("Lucidchart", "lucidsoftware"), ("Luminar", "luminartech"), ("Lyft", "lyft"),
    ("M1 Finance", "m1finance"), ("Malwarebytes", "malwarebytes"),
    ("Marqeta", "marqeta"), ("MasterClass", "masterclass"), ("Matterport", "matterport"),
    ("Medallia", "medallia"), ("Mercury", "mercury"), ("Miro", "miro"),
    ("Modern Health", "modernhealth"), ("Monday.com", "mondaydotcom"),
    ("MoneyLion", "moneylion"), ("MongoDB", "mongodb"), ("Monzo", "monzo"),
    ("Motive", "motive"), ("Moveworks", "moveworks"), ("Mural", "mural"),
    ("NerdWallet", "nerdwallet"), ("Netlify", "netlify"), ("New Relic", "newrelic"),
    ("Nextdoor", "nextdoor"), ("Niantic", "niantic"), ("Notion", "notion"),
    ("Nubank", "nubank"), ("Nuro", "nuro"), ("Nutanix", "nutanix"),
    ("Okta", "okta"), ("OneTrust", "onetrust"), ("OpenAI", "openai"),
    ("Opendoor", "opendoor"), ("OpenSea", "opensea"), ("OpenStore", "openstore"),
    ("Optimizely", "optimizely"), ("Orchard", "orchard"), ("Oscar Health", "oscar"),
    ("Outreach", "outreach"), ("Overjet", "overjet"), ("PagerDuty", "pagerduty"),
    ("Palantir", "palantir"), ("Palo Alto Networks", "paloaltonetworks"),
    ("Patreon", "patreon"), ("Paytm", "paytm"), ("Pendo", "pendo"),
    ("Persona", "persona"), ("Pilot", "pilot"), ("Pinwheel", "pinwheel"),
    ("Pinterest", "pinterest"), ("Plaid", "plaid"), ("Planet Labs", "planetlabs"),
    ("Postman", "postman"), ("Procore", "procore"), ("Productboard", "productboard"),
    ("Proofpoint", "proofpoint"), ("PubMatic", "pubmatic"), ("Pure Storage", "purestorage"),
    ("Qualtrics", "qualtrics"), ("Quizlet", "quizlet"), ("Ramp", "rampnetwork"),
    ("Rapid7", "rapid7"), ("Reddit", "reddit"), ("Redis", "redis"),
    ("Redfin", "redfin"), ("Relativity", "relativity"), ("Remitly", "remitly"),
    ("Remote", "remotecom"), ("Retool", "retool"), ("Revolut", "revolut"),
    ("Rippling", "rippling"), ("Rivian", "rivian"), ("Robinhood", "robinhood"),
    ("Roblox", "roblox"), ("Roku", "roku"), ("Runway", "runwayml"),
    ("Samsara", "samsara"), ("Scale AI", "scaleai"), ("SeatGeek", "seatgeek"),
    ("Segment", "segment"), ("SentinelOne", "sentinelone"), ("Sentry", "sentry"),
    ("ServiceTitan", "servicetitan"), ("Shopify", "shopify"), ("Sift", "sift"),
    ("SingleStore", "singlestore"), ("Skydio", "skydio"), ("Slack", "slack"),
    ("Smartsheet", "smartsheet"), ("Snap", "snapchat"), ("Snorkel", "snorkel"),
    ("Snyk", "snyk"), ("Sofi", "sofi"), ("Sonder", "sonder"),
    ("SoundCloud", "soundcloud"), ("SpaceX", "spacex"), ("Splunk", "splunk"),
    ("Spotify", "spotify"), ("Square", "square"), ("Squarespace", "squarespace"),
    ("StackAdapt", "stackadapt"), ("Stash", "stash"), ("Stitch Fix", "stitchfix"),
    ("Stripe", "stripe"), ("StubHub", "stubhub"), ("Sumo Logic", "sumologic"),
    ("Superhuman", "superhuman"), ("Superset", "superset"), ("Supabase", "supabase"),
    ("Suse", "suse"), ("Synack", "synack"), ("Synopsys", "synopsys"),
    ("Tanium", "tanium"), ("Tanium", "taniuminc"), ("Tanium", "tanium"),
    ("Tanium", "tanium"), ("Tanium", "tanium"),
    ("Tanium", "tanium"), ("Tenable", "tenable"), ("Tenstorrent", "tenstorrent"),
    ("Tesla", "tesla"), ("The Trade Desk", "thetradedesk"), ("Thumbtack", "thumbtack"),
    ("TikTok", "tiktok"), ("Toast", "toast"), ("Tonal", "tonal"),
    ("Trade Republic", "traderepublic"), ("Tradeshift", "tradeshift"),
    ("Transfix", "transfix"), ("TripActions", "tripactions"), ("Trumid", "trumid"),
    ("Twilio", "twilio"), ("Twitch", "twitch"), ("UiPath", "uipath"),
    ("Uniswap", "uniswap"), ("Unity", "unity3d"), ("Upstart", "upstart"),
    ("Vanta", "vanta"), ("Veeva", "veeva"), ("Vercel", "vercel"),
    ("Verkada", "verkada"), ("Vimeo", "vimeo"), ("Visa", "visa"),
    ("Viz.ai", "vizai"), ("VSCO", "vsco"), ("Watershed", "watershed"),
    ("Wayfair", "wayfair"), ("Waymo", "waymo"), ("Webflow", "webflow"),
    ("Weights & Biases", "wandb"), ("Whatnot", "whatnot"), ("Whoop", "whoop"),
    ("Wise", "wise"), ("Wish", "wish"), ("Wix", "wix"),
    ("Workday", "workday"), ("Workiva", "workiva"), ("Wunderkind", "wunderkind"),
    ("Yext", "yext"), ("Yieldmo", "yieldmo"), ("Zapier", "zapier"),
    ("Zendesk", "zendesk"), ("Zenefits", "zenefits"), ("ZeroFox", "zerofox"),
    ("Zip", "zip"), ("ZipRecruiter", "ziprecruiter"), ("Zocdoc", "zocdoc"),
    ("Zoom", "zoom"), ("ZoomInfo", "zoominfo"), ("Zscaler", "zscaler"),
    ("Zuora", "zuora"), ("Zynga", "zynga"),
    # Additional batch
    ("Abnormal Security", "abnormalsecurity"), ("Acquia", "acquia"),
    ("ActBlue", "actblue"), ("Adaptive Insights", "adaptiveinsights"),
    ("Affirm", "affirm"), ("Agility Robotics", "agilityrobotics"),
    ("Airship", "airship"), ("Akamai", "akamai"), ("Alteryx", "alteryx"),
    ("Amperity", "amperity"), ("Amplitude", "amplitude"), ("Anaplan", "anaplan"),
    ("Ankorstore", "ankorstore"), ("Ansys", "ansys"), ("Apptio", "apptio"),
    ("Arctic Wolf", "arcticwolf"), ("Arize AI", "arizeai"), ("Asana", "asana"),
    ("AssemblyAI", "assemblyai"), ("Attentive", "attentive"),
    ("Aurora Solar", "aurorasolar"), ("Automattic", "automattic"),
    ("Avalara", "avalara"), ("Aviatrix", "aviatrix"), ("Axon", "axon"),
    ("Bazaarvoice", "bazaarvoice"), ("BenchSci", "benchsci"),
    ("Betterment", "betterment"), ("BigCommerce", "bigcommerce"),
    ("Bill.com", "billcom"), ("Bird Rides", "bird"), ("Blackbaud", "blackbaud"),
    ("Blend", "blend"), ("Block", "block"), ("Blue Origin", "blueorigin"),
    ("Bolt Financial", "bolt"), ("Booking.com", "bookingcom"),
    ("Braze", "braze"), ("Brightcove", "brightcove"), ("Bumble", "bumble"),
    ("Calendly", "calendly"), ("CampusLogic", "campuslogic"),
    ("Canva", "canva"), ("Carbon", "carbon"), ("Carta", "carta"),
    ("Celigo", "celigo"), ("Census", "census"), ("Chainlink", "chainlink"),
    ("Chaos Industries", "chaosindustries"), ("Checkr", "checkr"),
    ("Chronicle", "chronicle"), ("Circle", "circle"), ("Citizen", "citizen"),
    ("Clarify Health", "clarifyhealth"), ("Clear", "clear"),
    ("ClickHouse", "clickhouse"), ("Cloudera", "cloudera"),
    ("Cloudflare", "cloudflare"), ("Cockroach Labs", "cockroachlabs"),
    ("Code42", "code42"), ("Cohere", "cohere"), ("Cohesity", "cohesity"),
    ("Collibra", "collibra"), ("Commure", "commure"), ("Compass", "compass"),
    ("Confluent", "confluent"), ("Conviva", "conviva"), ("Copper", "copper"),
    ("Corelight", "corelight"), ("Coupa", "coupa"), ("Coursera", "coursera"),
    ("Cribl", "cribl"), ("Crossbeam", "crossbeam"), ("Crusoe Energy", "crusoe"),
    ("CyberArk", "cyberark"), ("D2iQ", "d2iq"), ("Darktrace", "darktrace"),
    ("DataStax", "datastax"), ("Dataiku", "dataiku"), ("Dataminr", "dataminr"),
    ("Deel", "deel"), ("Deliverr", "deliverr"), ("Dialpad", "dialpad"),
    ("Discord", "discord"), ("Divvy", "divvy"), ("Domino Data Lab", "dominodatalab"),
    ("DoorDash", "doordashusa"), ("Drata", "drata"), ("Dropbox", "dropbox"),
    ("Druva", "druva"), ("Duolingo", "duolingo"), ("Dynatrace", "dynatrace"),
    ("Earnest", "earnest"), ("Elastic", "elastic"), ("Element Biosciences", "elementbiosciences"),
    ("Embark Trucks", "embarktrucks"), ("Enova", "enova"), ("Envoy", "envoy"),
    ("Epic Games", "epicgames"), ("Equinix", "equinix"), ("Esri", "esri"),
    ("Ethos", "ethos"), ("Eventbrite", "eventbrite"), ("Everlaw", "everlaw"),
    ("Exabeam", "exabeam"), ("Expel", "expel"), ("Expensify", "expensify"),
    ("F5", "f5"), ("Faire", "faire"), ("Fanatics", "fanatics"),
    ("Fastly", "fastly"), ("Fetch Rewards", "fetchrewards"),
    ("Figma", "figma"), ("Fireblocks", "fireblocks"), ("First Orion", "firstorion"),
    ("Five9", "five9"), ("Flex", "flex"), ("Flexport", "flexport"),
    ("Flipboard", "flipboard"), ("FloQast", "floqast"), ("Flutter", "flutter"),
    ("Form Energy", "formenergy"), ("Fortra", "fortra"), ("FreshBooks", "freshbooks"),
    ("Freshworks", "freshworks"), ("Front", "front"), ("FullStory", "fullstory"),
    ("Gainsight", "gainsight"), ("Galaxy Digital", "galaxydigital"),
    ("Gemini", "gemini"), ("Genesys", "genesys"), ("Ginkgo Bioworks", "ginkgobioworks"),
    ("GitLab", "gitlab"), ("Glean", "gleanwork"), ("GoCardless", "gocardless"),
    ("Gong", "gongio"), ("Gopuff", "gopuff"), ("Grammarly", "grammarly"),
    ("Greenhouse", "greenhouse"), ("Gusto", "gusto"), ("HackerRank", "hackerrank"),
    ("Handshake", "handshake"), ("Harness", "harness"), ("Hashicorp", "hashicorp"),
    ("Hazel", "hazel"), ("Headspace", "headspace"), ("Helion Energy", "helionenergy"),
    ("Hinge Health", "hingehealth"), ("Hopper", "hopper"), ("HubSpot", "hubspot"),
    ("Human Interest", "humaninterest"), ("Huntress", "huntress"),
    ("HyperScience", "hyperscience"), ("Icertis", "icertis"), ("Illumio", "illumio"),
    ("Imply", "imply"), ("Immuta", "immuta"), ("Impossible Foods", "impossiblefoods"),
    ("InVision", "invision"), ("Incorta", "incorta"), ("InfluxData", "influxdata"),
    ("Instacart", "instacart"), ("Instabase", "instabase"), ("Intercom", "intercom"),
    ("Invitae", "invitae"), ("Ironclad", "ironclad"), ("Iterable", "iterable"),
    ("Ivanti", "ivanti"), ("Jamf", "jamf"), ("Juniper Networks", "junipernetworks"),
    ("Justworks", "justworks"), ("Kajabi", "kajabi"), ("Kandji", "kandji"),
    ("Klaviyo", "klaviyo"), ("KnowBe4", "knowbe4"), ("Kong", "kong"),
    ("Kraken", "kraken"), ("Lacework", "lacework"), ("Lambda Labs", "lambdalabs"),
    ("Lattice", "lattice"), ("LaunchDarkly", "launchdarkly"), ("LeanData", "leandata"),
    ("Lemonade", "lemonade"), ("Lime", "lime"), ("Linear", "linear"),
    ("LiveRamp", "liveramp"), ("Locus Robotics", "locusrobotics"), ("Loom", "loom"),
    ("Lucid Motors", "lucidmotors"), ("Lyft", "lyft"), ("M1 Finance", "m1finance"),
    ("Malwarebytes", "malwarebytes"), ("Marqeta", "marqeta"), ("MasterClass", "masterclass"),
    ("Matterport", "matterport"), ("Medallia", "medallia"), ("Mercury", "mercury"),
    ("Miro", "miro"), ("Modern Treasury", "moderntreasury"), ("Monday.com", "mondaydotcom"),
    ("MoneyLion", "moneylion"), ("MongoDB", "mongodb"), ("Monzo", "monzo"),
    ("Motive", "motive"), ("Moveworks", "moveworks"), ("Mural", "mural"),
    ("NerdWallet", "nerdwallet"), ("Netlify", "netlify"), ("New Relic", "newrelic"),
    ("Next Insurance", "nextinsurance"), ("Nextdoor", "nextdoor"),
    ("Niantic", "niantic"), ("Notion", "notion"), ("Nubank", "nubank"),
    ("Nuro", "nuro"), ("Nutanix", "nutanix"), ("Observe", "observeinc"),
    ("Okta", "okta"), ("OneTrust", "onetrust"), ("OpenAI", "openai"),
    ("Opendoor", "opendoor"), ("OpenSea", "opensea"), ("Optimizely", "optimizely"),
    ("Orca Security", "orcasecurity"), ("Oscar Health", "oscar"), ("Outreach", "outreach"),
    ("Overjet", "overjet"), ("PagerDuty", "pagerduty"), ("Palantir", "palantir"),
    ("Palo Alto Networks", "paloaltonetworks"), ("Patreon", "patreon"),
    ("Pendo", "pendo"), ("Persona", "persona"), ("Pilot", "pilot"),
    ("Pinterest", "pinterest"), ("Plaid", "plaid"), ("Planet Labs", "planetlabs"),
    ("Postman", "postman"), ("Procore", "procore"), ("Productboard", "productboard"),
    ("Proofpoint", "proofpoint"), ("PubMatic", "pubmatic"), ("Pure Storage", "purestorage"),
    ("Qualtrics", "qualtrics"), ("Quizlet", "quizlet"), ("Ramp", "rampnetwork"),
    ("Rapid7", "rapid7"), ("Reddit", "reddit"), ("Redis", "redis"),
    ("Redfin", "redfin"), ("Relativity", "relativity"), ("Remitly", "remitly"),
    ("Remote", "remotecom"), ("Retool", "retool"), ("Revolut", "revolut"),
    ("Rippling", "rippling"), ("Rivian", "rivian"), ("Robinhood", "robinhood"),
    ("Roblox", "roblox"), ("Roku", "roku"), ("Runway", "runwayml"),
    ("Samsara", "samsara"), ("Scale AI", "scaleai"), ("SeatGeek", "seatgeek"),
    ("Segment", "segment"), ("SentinelOne", "sentinelone"), ("Sentry", "sentry"),
    ("ServiceTitan", "servicetitan"), ("Shopify", "shopify"), ("Sift", "sift"),
    ("SingleStore", "singlestore"), ("Skydio", "skydio"), ("Smartsheet", "smartsheet"),
    ("Snap", "snapchat"), ("Snorkel AI", "snorkel"), ("Snyk", "snyk"),
    ("SoFi", "sofi"), ("Sonder", "sonder"), ("SoundCloud", "soundcloud"),
    ("SpaceX", "spacex"), ("Splunk", "splunk"), ("Spotify", "spotify"),
    ("Squarespace", "squarespace"), ("StackAdapt", "stackadapt"),
    ("Stitch Fix", "stitchfix"), ("Stripe", "stripe"), ("StubHub", "stubhub"),
    ("Sumo Logic", "sumologic"), ("Superhuman", "superhuman"), ("Supabase", "supabase"),
    ("Suse", "suse"), ("Synack", "synack"), ("Tanium", "tanium"),
    ("Tenable", "tenable"), ("Tenstorrent", "tenstorrent"), ("Tesla", "tesla"),
    ("The Trade Desk", "thetradedesk"), ("Thumbtack", "thumbtack"),
    ("Toast", "toast"), ("Tonal", "tonal"), ("Trade Republic", "traderepublic"),
    ("Transfix", "transfix"), ("TripActions", "tripactions"), ("Trumid", "trumid"),
    ("Twilio", "twilio"), ("Twitch", "twitch"), ("UiPath", "uipath"),
    ("Unity", "unity3d"), ("Upstart", "upstart"), ("Vanta", "vanta"),
    ("Veeva", "veeva"), ("Vercel", "vercel"), ("Verkada", "verkada"),
    ("Vimeo", "vimeo"), ("Viz.ai", "vizai"), ("Watershed", "watershed"),
    ("Wayfair", "wayfair"), ("Waymo", "waymo"), ("Webflow", "webflow"),
    ("Whatnot", "whatnot"), ("Whoop", "whoop"), ("Wise", "wise"),
    ("Wix", "wix"), ("Workiva", "workiva"), ("Yext", "yext"),
    ("Zapier", "zapier"), ("Zendesk", "zendesk"), ("ZeroFox", "zerofox"),
    ("Zip", "zip"), ("Zocdoc", "zocdoc"), ("Zoom", "zoom"),
    ("ZoomInfo", "zoominfo"), ("Zscaler", "zscaler"), ("Zuora", "zuora"),
]

# (display_name, tenant, wd_server, site)
WORKDAY_CANDIDATES = [
    ("Adobe", "adobe", "wd5", "external_experienced"),
    ("BlackRock", "blackrock", "wd1", "BlackRock_Professional"),
    ("Broadcom", "broadcom", "wd1", "External_Career"),
    ("Cadence", "cadence", "wd1", "External_Careers"),
    ("Cisco", "cisco", "wd5", "Cisco_Careers"),
    ("Citi", "citi", "wd5", "2"),
    ("Dell", "dell", "wd1", "External"),
    ("HP", "hp", "wd5", "ExternalCareerSite"),
    ("Marvell", "marvell", "wd1", "MarvellCareers"),
    ("Mastercard", "mastercard", "wd1", "CorporateCareers"),
    ("Micron", "micron", "wd1", "External"),
    ("Nasdaq", "nasdaq", "wd1", "Global_External_Site"),
    ("Nike", "nike", "wd1", "nke"),
    ("NVIDIA", "nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("PayPal", "paypal", "wd1", "jobs"),
    ("Salesforce", "salesforce", "wd12", "External_Career_Site"),
    ("Visa", "visa", "wd5", "Visa"),
    ("Applied Materials", "amat", "wd1", "External"),
    ("Intel", "intel", "wd1", "External"),
    # Extra workday probes with alternate configs
    ("Netflix", "netflix", "wd1", "Netflix"),
    ("Netflix", "netflix", "wd1", "External"),
    ("Netflix", "netflix", "wd1", "jobs"),
    ("Microsoft", "microsoft", "wd1", "Careers"),
    ("Microsoft", "microsoft", "wd1", "External"),
    ("Microsoft", "microsoft", "wd1", "MSFT"),
    ("ServiceNow", "servicenow", "wd1", "Careers"),
    ("ServiceNow", "servicenow", "wd1", "External"),
    ("Intuit", "intuit", "wd1", "Intuit"),
    ("Intuit", "intuit", "wd1", "External"),
    ("AMD", "amd", "wd1", "External"),
    ("AMD", "amd", "wd1", "AMD"),
    ("IBM", "ibm", "wd1", "IBM"),
    ("IBM", "ibm", "wd1", "External"),
    ("Oracle", "oracle", "wd1", "Oracle"),
    ("Oracle", "oracle", "wd1", "External"),
    ("SAP", "sap", "wd3", "SAPCareers"),
    ("SAP", "sap", "wd3", "External"),
    ("Qualcomm", "qualcomm", "wd1", "External"),
    ("Qualcomm", "qualcomm", "wd1", "Qualcomm"),
    ("Texas Instruments", "texasinstruments", "wd1", "TI"),
    ("Texas Instruments", "ti", "wd1", "External"),
    ("Amazon", "amazon", "wd5", "Amazon"),
    ("Amazon", "amazon", "wd5", "External"),
    ("Amazon", "amazon", "wd5", "Jobs"),
    ("Synopsys", "synopsys", "wd1", "Synopsys_Careers"),
    ("Synopsys", "synopsys", "wd1", "External"),
    ("Siemens", "siemens", "wd3", "Siemens_Careers"),
    ("Siemens", "siemens", "wd3", "External"),
    ("Honeywell", "honeywell", "wd5", "Honeywell"),
    ("Honeywell", "honeywell", "wd5", "External"),
    ("GE", "ge", "wd5", "GE_External_Site"),
    ("GE", "ge", "wd5", "External"),
    ("GE Vernova", "gevernova", "wd5", "External"),
    ("Johnson & Johnson", "jj", "wd5", "External"),
    ("J&J", "jnj", "wd5", "External"),
    ("Pfizer", "pfizer", "wd1", "External"),
    ("Merck", "msd", "wd5", "External"),
    ("Abbott", "abbott", "wd5", "External"),
    ("Medtronic", "medtronic", "wd1", "External"),
    ("Thermo Fisher", "thermofisher", "wd5", "External"),
    ("Danaher", "danaher", "wd1", "External"),
    ("Boston Scientific", "bostonscientific", "wd1", "External"),
    ("Starbucks", "starbucks", "wd1", "External"),
    ("PepsiCo", "pepsico", "wd5", "External"),
    ("Procter & Gamble", "pg", "wdTQ9", "External"),
    ("Procter & Gamble", "pg", "wd5", "External"),
    ("Unilever", "unilever", "wd3", "External"),
    ("Colgate", "colgate", "wd1", "External"),
    ("Marriott", "marriott", "wd1", "External"),
    ("Hilton", "hilton", "wd1", "External"),
    ("FedEx", "fedex", "wd1", "External"),
    ("UPS", "ups", "wd5", "External"),
    ("Home Depot", "homedepot", "wd5", "External"),
    ("Lowe's", "lowes", "wd5", "External"),
    ("Target", "target", "wd5", "External"),
    ("Walmart", "walmart", "wd5", "External"),
    ("Costco", "costco", "wd1", "External"),
    ("Best Buy", "bestbuy", "wd5", "External"),
    ("Gap", "gapinc", "wd1", "External"),
    ("Lululemon", "lululemon", "wd1", "External"),
    ("Under Armour", "underarmour", "wd1", "External"),
    ("3M", "3m", "wd1", "External"),
    ("Caterpillar", "cat", "wd1", "External"),
    ("John Deere", "johndeere", "wd1", "External"),
    ("Honeywell", "honeywell", "wd5", "Honeywell"),
    ("Emerson", "emerson", "wd1", "External"),
    ("Rockwell", "rockwellautomation", "wd1", "External"),
    ("Trimble", "trimble", "wd1", "External"),
    ("Autodesk", "autodesk", "wd1", "External"),
    ("Ansys", "ansys", "wd1", "External"),
    ("Synopsys", "synopsys", "wd1", "Synopsys_Careers"),
    ("Marvell", "marvell", "wd1", "MarvellCareers"),
    ("Western Digital", "wdc", "wd1", "External"),
    ("Seagate", "seagate", "wd1", "External"),
    ("KLA", "kla", "wd1", "External"),
    ("Lam Research", "lamresearch", "wd1", "External"),
    ("ASML", "asml", "wd1", "External"),
    ("TSMC", "tsmc", "wd1", "External"),
    ("Motorola", "motorola", "wd1", "External"),
    ("Ericsson", "ericsson", "wd1", "External"),
    ("Nokia", "nokia", "wd1", "External"),
    ("Philips", "philips", "wd3", "External"),
    ("Siemens Healthineers", "siemenshealthineers", "wd3", "External"),
    ("Workday", "workday", "wd5", "Workday"),
    ("Splunk", "splunk", "wd5", "External"),
    ("Palo Alto Networks", "paloaltonetworks", "wd1", "External"),
    ("Fortinet", "fortinet", "wd1", "External"),
    ("CrowdStrike", "crowdstrike", "wd1", "External"),
    ("Zscaler", "zscaler", "wd1", "External"),
    ("Okta", "okta", "wd1", "External"),
    ("Snowflake", "snowflake", "wd1", "External"),
    ("Datadog", "datadog", "wd1", "External"),
    ("MongoDB", "mongodb", "wd1", "External"),
    ("Atlassian", "atlassian", "wd1", "External"),
    ("HubSpot", "hubspot", "wd1", "External"),
    ("Twilio", "twilio", "wd1", "External"),
    ("DocuSign", "docusign", "wd1", "External"),
    ("Zoom", "zoom", "wd1", "External"),
    ("Block", "block", "wd1", "External"),
    ("Coinbase", "coinbase", "wd1", "External"),
    ("Robinhood", "robinhood", "wd1", "External"),
    ("Affirm", "affirm", "wd1", "External"),
    ("SoFi", "sofi", "wd1", "External"),
    ("Chime", "chime", "wd1", "External"),
    ("Brex", "brex", "wd1", "External"),
    ("Plaid", "plaid", "wd1", "External"),
    ("Ramp", "ramp", "wd1", "External"),
    ("Rippling", "rippling", "wd1", "External"),
    ("Gusto", "gusto", "wd1", "External"),
    ("Deel", "deel", "wd1", "External"),
    ("Stripe", "stripe", "wd1", "External"),
    ("Airbnb", "airbnb", "wd1", "External"),
    ("Uber", "uber", "wd1", "External"),
    ("Lyft", "lyft", "wd1", "External"),
    ("DoorDash", "doordash", "wd1", "External"),
    ("Instacart", "instacart", "wd1", "External"),
    ("Pinterest", "pinterest", "wd1", "External"),
    ("Snap", "snap", "wd1", "External"),
    ("Reddit", "reddit", "wd1", "External"),
    ("Roblox", "roblox", "wd1", "External"),
    ("Unity", "unity", "wd1", "External"),
    ("Epic Games", "epicgames", "wd1", "External"),
    ("Riot Games", "riotgames", "wd1", "External"),
    ("Electronic Arts", "ea", "wd1", "External"),
    ("Take-Two", "take2games", "wd1", "External"),
    ("Activision", "activision", "wd1", "External"),
    ("Tesla", "tesla", "wd1", "External"),
    ("Rivian", "rivian", "wd1", "External"),
    ("Lucid", "lucidmotors", "wd1", "External"),
    ("Waymo", "waymo", "wd1", "External"),
    ("Cruise", "getcruise", "wd1", "External"),
    ("SpaceX", "spacex", "wd1", "External"),
    ("Anduril", "anduril", "wd1", "External"),
    ("Palantir", "palantir", "wd1", "External"),
    ("Scale AI", "scaleai", "wd1", "External"),
    ("OpenAI", "openai", "wd1", "External"),
    ("Anthropic", "anthropic", "wd1", "External"),
    ("Cohere", "cohere", "wd1", "External"),
    ("Hugging Face", "huggingface", "wd1", "External"),
    ("Mistral", "mistral", "wd1", "External"),
    ("Perplexity", "perplexity", "wd1", "External"),
    ("Databricks", "databricks", "wd1", "External"),
    ("Confluent", "confluent", "wd1", "External"),
    ("Elastic", "elastic", "wd1", "External"),
    ("HashiCorp", "hashicorp", "wd1", "External"),
    ("GitLab", "gitlab", "wd1", "External"),
    ("GitHub", "github", "wd1", "External"),
    ("JFrog", "jfrog", "wd1", "External"),
    ("Snyk", "snyk", "wd1", "External"),
    ("Wiz", "wiz", "wd1", "External"),
    ("SentinelOne", "sentinelone", "wd1", "External"),
    ("Rubrik", "rubrik", "wd1", "External"),
    ("Cohesity", "cohesity", "wd1", "External"),
    ("Pure Storage", "purestorage", "wd1", "External"),
    ("NetApp", "netapp", "wd1", "External"),
    ("Veeva", "veeva", "wd1", "External"),
    ("ServiceNow", "servicenow", "wd1", "External"),
    ("Salesforce", "salesforce", "wd12", "External_Career_Site"),
    ("Workday", "workday", "wd5", "Workday"),
    ("SAP", "sap", "wd3", "SAPCareers"),
    ("Oracle", "oracle", "wd1", "Oracle"),
    ("IBM", "ibm", "wd1", "IBM"),
    ("Accenture", "accenture", "wd103", "External"),
    ("Capgemini", "capgemini", "wd3", "External"),
    ("Infosys", "infosys", "wd1", "External"),
    ("Wipro", "wipro", "wd5", "External"),
    ("TCS", "tcs", "wd1", "External"),
    ("HCL", "hcltech", "wd1", "External"),
    ("Cognizant", "cognizant", "wd1", "External"),
    ("Tech Mahindra", "techmahindra", "wd1", "External"),
    ("LTIMindtree", "ltimindtree", "wd1", "External"),
    ("Persistent", "persistent", "wd1", "External"),
    ("Mphasis", "mphasis", "wd1", "External"),
    ("Zensar", "zensar", "wd1", "External"),
    ("Virtusa", "virtusa", "wd1", "External"),
    ("Hexaware", "hexaware", "wd1", "External"),
    ("Coforge", "coforge", "wd1", "External"),
    ("L&T Technology", "lnttechservices", "wd1", "External"),
    ("Cyient", "cyient", "wd1", "External"),
    ("KPIT", "kpit", "wd1", "External"),
    ("Sonata", "sonata", "wd1", "External"),
    ("Mindtree", "mindtree", "wd1", "External"),
    ("Mastek", "mastek", "wd1", "External"),
    ("Birlasoft", "birlasoft", "wd1", "External"),
    ("NTT Data", "nttdata", "wd1", "External"),
    ("Deloitte", "deloitte", "wd1", "External"),
    ("EY", "ey", "wd1", "External"),
    ("KPMG", "kpmg", "wd1", "External"),
    ("PwC", "pwc", "wd1", "External"),
    ("McKinsey", "mckinsey", "wd1", "External"),
    ("BCG", "bcg", "wd1", "External"),
    ("Bain", "bain", "wd1", "External"),
]
