companies = [
    # LinkedIn (unofficial public search, no auth — see fetchers.linkedin_jobs)
    {
        "name": "LinkedIn",
        "type": "linkedin",
        "keywords": "software engineer OR data engineer OR machine learning engineer",
        "location": "India",
    },
    # Greenhouse (URL-tested)
    {"name": "Abnormal Security", "type": "greenhouse", "board": "abnormalsecurity"},
    {"name": "Adyen", "type": "greenhouse", "board": "adyen"},
    {"name": "Affirm", "type": "greenhouse", "board": "affirm"},
    {"name": "Airbnb", "type": "greenhouse", "board": "airbnb"},
    {"name": "Airtable", "type": "greenhouse", "board": "airtable"},
    {"name": "Alloy", "type": "greenhouse", "board": "alloy"},
    {"name": "AlphaSense", "type": "greenhouse", "board": "alphasense"},
    {"name": "Amperity", "type": "greenhouse", "board": "amperity"},
    {"name": "Amplitude", "type": "greenhouse", "board": "amplitude"},
    {"name": "Anaplan", "type": "greenhouse", "board": "anaplan"},
    {"name": "Anthropic", "type": "greenhouse", "board": "anthropic"},
    {"name": "Appian", "type": "greenhouse", "board": "appian"},
    {"name": "AppLovin", "type": "greenhouse", "board": "applovin"},
    {"name": "Asana", "type": "greenhouse", "board": "asana"},
    {"name": "Attentive", "type": "greenhouse", "board": "attentive"},
    {"name": "Aurora", "type": "greenhouse", "board": "aurorainnovation"},
    {"name": "Axon", "type": "greenhouse", "board": "axon"},
    {"name": "Axonius", "type": "greenhouse", "board": "axonius"},
    {"name": "Bill.com", "type": "greenhouse", "board": "billcom"},
    {"name": "Bird", "type": "greenhouse", "board": "bird"},
    {"name": "BitGo", "type": "greenhouse", "board": "bitgo"},
    {"name": "Blend", "type": "greenhouse", "board": "blend"},
    {"name": "Block", "type": "greenhouse", "board": "block"},
    {"name": "Box", "type": "greenhouse", "board": "boxinc"},
    {"name": "Branch", "type": "greenhouse", "board": "branch"},
    {"name": "Braze", "type": "greenhouse", "board": "braze"},
    {"name": "Brex", "type": "greenhouse", "board": "brex"},
    {"name": "Calendly", "type": "greenhouse", "board": "calendly"},
    {"name": "Calm", "type": "greenhouse", "board": "calm"},
    {"name": "Candid", "type": "greenhouse", "board": "candid"},
    {"name": "CarGurus", "type": "greenhouse", "board": "cargurus"},
    {"name": "Carta", "type": "greenhouse", "board": "carta"},
    {"name": "Carvana", "type": "greenhouse", "board": "carvana"},
    {"name": "Celonis", "type": "greenhouse", "board": "celonis"},
    {"name": "Chainguard", "type": "greenhouse", "board": "chainguard"},
    {"name": "Checkr", "type": "greenhouse", "board": "checkr"},
    {"name": "Chime", "type": "greenhouse", "board": "chime"},
    {"name": "Clear", "type": "greenhouse", "board": "clear"},
    {"name": "Cloudflare", "type": "greenhouse", "board": "cloudflare"},
    {"name": "Cockroach Labs", "type": "greenhouse", "board": "cockroachlabs"},
    {"name": "Coinbase", "type": "greenhouse", "board": "coinbase"},
    {"name": "Collibra", "type": "greenhouse", "board": "collibra"},
    {"name": "Contentful", "type": "greenhouse", "board": "contentful"},
    {"name": "CoreWeave", "type": "greenhouse", "board": "coreweave"},
    {"name": "Coursera", "type": "greenhouse", "board": "coursera"},
    {"name": "Credit Karma", "type": "greenhouse", "board": "creditkarma"},
    {"name": "Crossbeam", "type": "greenhouse", "board": "crossbeam"},
    {"name": "Crunchyroll", "type": "greenhouse", "board": "crunchyroll"},
    {"name": "Culture Amp", "type": "greenhouse", "board": "cultureamp"},
    {"name": "Current", "type": "greenhouse", "board": "current"},
    {"name": "Dashlane", "type": "greenhouse", "board": "dashlane"},
    {"name": "Databricks", "type": "greenhouse", "board": "databricks"},
    {"name": "Datadog", "type": "greenhouse", "board": "datadog"},
    {"name": "Dataiku", "type": "greenhouse", "board": "dataiku"},
    {"name": "dbt Labs", "type": "greenhouse", "board": "dbtlabsinc"},
    {"name": "DeepMind", "type": "greenhouse", "board": "deepmind"},
    {"name": "Dialpad", "type": "greenhouse", "board": "dialpad"},
    {"name": "Discord", "type": "greenhouse", "board": "discord"},
    {"name": "DoorDash", "type": "greenhouse", "board": "doordashusa"},
    {"name": "DriveWealth", "type": "greenhouse", "board": "drivewealth"},
    {"name": "Dropbox", "type": "greenhouse", "board": "dropbox"},
    {"name": "Duolingo", "type": "greenhouse", "board": "duolingo"},
    {"name": "EarnIn", "type": "greenhouse", "board": "earnin"},
    {"name": "Elastic", "type": "greenhouse", "board": "elastic"},
    {"name": "Element Biosciences", "type": "greenhouse", "board": "elementbiosciences"},
    {"name": "Epic Games", "type": "greenhouse", "board": "epicgames"},
    {"name": "Ethos", "type": "greenhouse", "board": "ethos"},
    {"name": "Everlaw", "type": "greenhouse", "board": "everlaw"},
    {"name": "Exabeam", "type": "greenhouse", "board": "exabeam"},
    {"name": "Expel", "type": "greenhouse", "board": "expel"},
    {"name": "Extend", "type": "greenhouse", "board": "extend"},
    {"name": "Faire", "type": "greenhouse", "board": "faire"},
    {"name": "Farfetch", "type": "greenhouse", "board": "farfetch"},
    {"name": "Fastly", "type": "greenhouse", "board": "fastly"},
    {"name": "Figma", "type": "greenhouse", "board": "figma"},
    {"name": "Fivetran", "type": "greenhouse", "board": "fivetran"},
    {"name": "Flatiron Health", "type": "greenhouse", "board": "flatironhealth"},
    {"name": "Flexport", "type": "greenhouse", "board": "flexport"},
    {"name": "Formlabs", "type": "greenhouse", "board": "formlabs"},
    {"name": "Forward", "type": "greenhouse", "board": "forward"},
    {"name": "Found", "type": "greenhouse", "board": "found"},
    {"name": "GetYourGuide", "type": "greenhouse", "board": "getyourguide"},
    {"name": "GitLab", "type": "greenhouse", "board": "gitlab"},
    {"name": "Glean", "type": "greenhouse", "board": "gleanwork"},
    {"name": "Glossier", "type": "greenhouse", "board": "glossier"},
    {"name": "GoFundMe", "type": "greenhouse", "board": "gofundme"},
    {"name": "Gong", "type": "greenhouse", "board": "gongio"},
    {"name": "Grafana Labs", "type": "greenhouse", "board": "grafanalabs"},
    {"name": "Greenhouse", "type": "greenhouse", "board": "greenhouse"},
    {"name": "Gusto", "type": "greenhouse", "board": "gusto"},
    {"name": "Hazel", "type": "greenhouse", "board": "hazel"},
    {"name": "Honeycomb", "type": "greenhouse", "board": "honeycomb"},
    {"name": "HubSpot", "type": "greenhouse", "board": "hubspot"},
    {"name": "Human Interest", "type": "greenhouse", "board": "humaninterest"},
    {"name": "Huntress", "type": "greenhouse", "board": "huntress"},
    {"name": "Imply", "type": "greenhouse", "board": "imply"},
    {"name": "Indigo", "type": "greenhouse", "board": "indigo"},
    {"name": "Instabase", "type": "greenhouse", "board": "instabase"},
    {"name": "Instacart", "type": "greenhouse", "board": "instacart"},
    {"name": "Instawork", "type": "greenhouse", "board": "instawork"},
    {"name": "Intercom", "type": "greenhouse", "board": "intercom"},
    {"name": "Iterable", "type": "greenhouse", "board": "iterable"},
    {"name": "JetBrains", "type": "greenhouse", "board": "jetbrains"},
    {"name": "JFrog", "type": "greenhouse", "board": "jfrog"},
    {"name": "Justworks", "type": "greenhouse", "board": "justworks"},
    {"name": "Klaviyo", "type": "greenhouse", "board": "klaviyo"},
    {"name": "Lattice", "type": "greenhouse", "board": "lattice"},
    {"name": "LaunchDarkly", "type": "greenhouse", "board": "launchdarkly"},
    {"name": "LinkedIn", "type": "greenhouse", "board": "linkedin"},
    {"name": "LogicMonitor", "type": "greenhouse", "board": "logicmonitor"},
    {"name": "Lucid Motors", "type": "greenhouse", "board": "lucidmotors"},
    {"name": "Lyft", "type": "greenhouse", "board": "lyft"},
    {"name": "Magic Leap", "type": "greenhouse", "board": "magicleap"},
    {"name": "Marqeta", "type": "greenhouse", "board": "marqeta"},
    {"name": "MasterClass", "type": "greenhouse", "board": "masterclass"},
    {"name": "Maven Clinic", "type": "greenhouse", "board": "mavenclinic"},
    {"name": "Medium", "type": "greenhouse", "board": "medium"},
    {"name": "Mercury", "type": "greenhouse", "board": "mercury"},
    {"name": "Mesh", "type": "greenhouse", "board": "mesh"},
    {"name": "Mixpanel", "type": "greenhouse", "board": "mixpanel"},
    {"name": "Modern Health", "type": "greenhouse", "board": "modernhealth"},
    {"name": "Moloco", "type": "greenhouse", "board": "moloco"},
    {"name": "MongoDB", "type": "greenhouse", "board": "mongodb"},
    {"name": "Monzo", "type": "greenhouse", "board": "monzo"},
    {"name": "Motive", "type": "greenhouse", "board": "motive"},
    {"name": "N26", "type": "greenhouse", "board": "n26"},
    {"name": "Navan", "type": "greenhouse", "board": "tripactions"},
    {"name": "Netlify", "type": "greenhouse", "board": "netlify"},
    {"name": "New Relic", "type": "greenhouse", "board": "newrelic"},
    {"name": "Nextdoor", "type": "greenhouse", "board": "nextdoor"},
    {"name": "Nubank", "type": "greenhouse", "board": "nubank"},
    {"name": "Nuro", "type": "greenhouse", "board": "nuro"},
    {"name": "Okta", "type": "greenhouse", "board": "okta"},
    {"name": "One Medical", "type": "greenhouse", "board": "onemedical"},
    {"name": "OneTrust", "type": "greenhouse", "board": "onetrust"},
    {"name": "Orca Security", "type": "greenhouse", "board": "orcasecurity"},
    {"name": "Oscar Health", "type": "greenhouse", "board": "oscar"},
    {"name": "Pacaso", "type": "greenhouse", "board": "pacaso"},
    {"name": "PagerDuty", "type": "greenhouse", "board": "pagerduty"},
    {"name": "Pendo", "type": "greenhouse", "board": "pendo"},
    {"name": "Pinterest", "type": "greenhouse", "board": "pinterest"},
    {"name": "Planet Labs", "type": "greenhouse", "board": "planetlabs"},
    {"name": "Postman", "type": "greenhouse", "board": "postman"},
    {"name": "PubMatic", "type": "greenhouse", "board": "pubmatic"},
    {"name": "Pure Storage", "type": "greenhouse", "board": "purestorage"},
    {"name": "Qualtrics", "type": "greenhouse", "board": "qualtrics"},
    {"name": "Ramp", "type": "greenhouse", "board": "rampnetwork"},
    {"name": "Recorded Future", "type": "greenhouse", "board": "recordedfuture"},
    {"name": "Reddit", "type": "greenhouse", "board": "reddit"},
    {"name": "Relativity", "type": "greenhouse", "board": "relativity"},
    {"name": "Remote", "type": "greenhouse", "board": "remotecom"},
    {"name": "Riot Games", "type": "greenhouse", "board": "riotgames"},
    {"name": "Robinhood", "type": "greenhouse", "board": "robinhood"},
    {"name": "Roblox", "type": "greenhouse", "board": "roblox"},
    {"name": "Rocket Lab", "type": "greenhouse", "board": "rocketlab"},
    {"name": "Roku", "type": "greenhouse", "board": "roku"},
    {"name": "Roofstock", "type": "greenhouse", "board": "roofstock"},
    {"name": "Rubrik", "type": "greenhouse", "board": "rubrik"},
    {"name": "Samsara", "type": "greenhouse", "board": "samsara"},
    {"name": "Scale AI", "type": "greenhouse", "board": "scaleai"},
    {"name": "SeatGeek", "type": "greenhouse", "board": "seatgeek"},
    {"name": "Sigma Computing", "type": "greenhouse", "board": "sigmacomputing"},
    {"name": "SingleStore", "type": "greenhouse", "board": "singlestore"},
    {"name": "SmartAsset", "type": "greenhouse", "board": "smartasset"},
    {"name": "Smartsheet", "type": "greenhouse", "board": "smartsheet"},
    {"name": "Snorkel AI", "type": "greenhouse", "board": "snorkelai"},
    {"name": "SoFi", "type": "greenhouse", "board": "sofi"},
    {"name": "Sourcegraph", "type": "greenhouse", "board": "sourcegraph91"},
    {"name": "SpaceX", "type": "greenhouse", "board": "spacex"},
    {"name": "Squarespace", "type": "greenhouse", "board": "squarespace"},
    {"name": "Stability AI", "type": "greenhouse", "board": "stabilityai"},
    {"name": "Stitch Fix", "type": "greenhouse", "board": "stitchfix"},
    {"name": "StockX", "type": "greenhouse", "board": "stockx"},
    {"name": "Stripe", "type": "greenhouse", "board": "stripe"},
    {"name": "Sumo Logic", "type": "greenhouse", "board": "sumologic"},
    {"name": "SurveyMonkey", "type": "greenhouse", "board": "surveymonkey"},
    {"name": "Taboola", "type": "greenhouse", "board": "taboola"},
    {"name": "Tailscale", "type": "greenhouse", "board": "tailscale"},
    {"name": "Tanium", "type": "greenhouse", "board": "tanium"},
    {"name": "TaskRabbit", "type": "greenhouse", "board": "taskrabbit"},
    {"name": "Toast", "type": "greenhouse", "board": "toast"},
    {"name": "TripActions", "type": "greenhouse", "board": "tripactions"},
    {"name": "Trumid", "type": "greenhouse", "board": "trumid"},
    {"name": "Twilio", "type": "greenhouse", "board": "twilio"},
    {"name": "Udemy", "type": "greenhouse", "board": "udemy"},
    {"name": "Upstart", "type": "greenhouse", "board": "upstart"},
    {"name": "Upwork", "type": "greenhouse", "board": "upwork"},
    {"name": "Vercel", "type": "greenhouse", "board": "vercel"},
    {"name": "Verkada", "type": "greenhouse", "board": "verkada"},
    {"name": "Watershed", "type": "greenhouse", "board": "watershed"},
    {"name": "Waymo", "type": "greenhouse", "board": "waymo"},
    {"name": "Webflow", "type": "greenhouse", "board": "webflow"},
    {"name": "Wikimedia", "type": "greenhouse", "board": "wikimedia"},
    {"name": "Wiz", "type": "greenhouse", "board": "wizinc"},
    {"name": "Wolt", "type": "greenhouse", "board": "wolt"},
    {"name": "Workato", "type": "greenhouse", "board": "workato"},
    {"name": "Yext", "type": "greenhouse", "board": "yext"},
    {"name": "Yotpo", "type": "greenhouse", "board": "yotpo"},
    {"name": "ZipRecruiter", "type": "greenhouse", "board": "ziprecruiter"},
    {"name": "Zocdoc", "type": "greenhouse", "board": "zocdoc"},
    {"name": "Zscaler", "type": "greenhouse", "board": "zscaler"},
    {"name": "Zuora", "type": "greenhouse", "board": "zuora"},
    # Workday (URL-tested)
    {"name": "Adobe", "type": "workday", "tenant": "adobe", "wd_server": "wd5", "site": "external_experienced"},
    {"name": "Analog Devices", "type": "workday", "tenant": "analogdevices", "wd_server": "wd1", "site": "External"},
    {"name": "Applied Materials", "type": "workday", "tenant": "amat", "wd_server": "wd1", "site": "External"},
    {"name": "BlackRock", "type": "workday", "tenant": "blackrock", "wd_server": "wd1", "site": "BlackRock_Professional"},
    {"name": "Broadcom", "type": "workday", "tenant": "broadcom", "wd_server": "wd1", "site": "External_Career"},
    {"name": "Cadence", "type": "workday", "tenant": "cadence", "wd_server": "wd1", "site": "External_Careers"},
    {"name": "Cisco", "type": "workday", "tenant": "cisco", "wd_server": "wd5", "site": "Cisco_Careers"},
    {"name": "Citi", "type": "workday", "tenant": "citi", "wd_server": "wd5", "site": "2"},
    {"name": "Dell", "type": "workday", "tenant": "dell", "wd_server": "wd1", "site": "External"},
    {"name": "HP", "type": "workday", "tenant": "hp", "wd_server": "wd5", "site": "ExternalCareerSite"},
    {"name": "Intel", "type": "workday", "tenant": "intel", "wd_server": "wd1", "site": "External"},
    {"name": "Marvell", "type": "workday", "tenant": "marvell", "wd_server": "wd1", "site": "MarvellCareers"},
    {"name": "Mastercard", "type": "workday", "tenant": "mastercard", "wd_server": "wd1", "site": "CorporateCareers"},
    {"name": "Micron", "type": "workday", "tenant": "micron", "wd_server": "wd1", "site": "External"},
    {"name": "Nasdaq", "type": "workday", "tenant": "nasdaq", "wd_server": "wd1", "site": "Global_External_Site"},
    {"name": "Nike", "type": "workday", "tenant": "nike", "wd_server": "wd1", "site": "nke"},
    {"name": "NVIDIA", "type": "workday", "tenant": "nvidia", "wd_server": "wd5", "site": "NVIDIAExternalCareerSite"},
    {"name": "NXP", "type": "workday", "tenant": "nxp", "wd_server": "wd3", "site": "Careers"},
    {"name": "PayPal", "type": "workday", "tenant": "paypal", "wd_server": "wd1", "site": "jobs"},
    {"name": "Qualcomm", "type": "workday", "tenant": "qualcomm", "wd_server": "wd12", "site": "External"},
    {"name": "Salesforce", "type": "workday", "tenant": "salesforce", "wd_server": "wd12", "site": "External_Career_Site"},
    {"name": "State Street", "type": "workday", "tenant": "statestreet", "wd_server": "wd1", "site": "Global"},
    {"name": "T-Mobile", "type": "workday", "tenant": "tmobile", "wd_server": "wd1", "site": "External"},
    {"name": "Visa", "type": "workday", "tenant": "visa", "wd_server": "wd5", "site": "Visa"},
    {"name": "Workday", "type": "workday", "tenant": "workday", "wd_server": "wd5", "site": "Workday"},
]
