companies = [
    {
        "name": "Anthropic",
        "type": "greenhouse",
        "board": "anthropic",
    },
    {
        "name": "Stripe",
        "type": "greenhouse",
        "board": "stripe",
    },
    {
        "name": "Figma",
        "type": "greenhouse",
        "board": "figma",
    },
    {
        "name": "Netflix",
        "type": "workday",
        "tenant": "netflix",
        "wd_server": "wd1",
        "site": "Netflix",
    },
    {
        "name": "Microsoft",
        "type": "workday",
        "tenant": "microsoft",
        "wd_server": "wd1",
        "site": "Careers",
    },
    # Banks / large financial institutions
    {
        "name": "Citi",
        "type": "workday",
        "tenant": "citi",
        "wd_server": "wd5",
        "site": "2",
    },
    {
        "name": "Visa",
        "type": "workday",
        "tenant": "visa",
        "wd_server": "wd5",
        "site": "Visa",
    },
    {
        "name": "Mastercard",
        "type": "workday",
        "tenant": "mastercard",
        "wd_server": "wd1",
        "site": "CorporateCareers",
    },
    {
        "name": "PayPal",
        "type": "workday",
        "tenant": "paypal",
        "wd_server": "wd1",
        "site": "jobs",
    },
    {
        "name": "Nasdaq",
        "type": "workday",
        "tenant": "nasdaq",
        "wd_server": "wd1",
        "site": "Global_External_Site",
    },
    {
        "name": "BlackRock",
        "type": "workday",
        "tenant": "blackrock",
        "wd_server": "wd1",
        "site": "BlackRock_Professional",
    },
    # Tech
    {
        "name": "Adobe",
        "type": "workday",
        "tenant": "adobe",
        "wd_server": "wd5",
        "site": "external_experienced",
    },
    # Fintech (Greenhouse boards)
    {
        "name": "Robinhood",
        "type": "greenhouse",
        "board": "robinhood",
    },
    {
        "name": "Coinbase",
        "type": "greenhouse",
        "board": "coinbase",
    },
    {
        "name": "Brex",
        "type": "greenhouse",
        "board": "brex",
    },
    {
        "name": "Affirm",
        "type": "greenhouse",
        "board": "affirm",
    },
    {
        "name": "Chime",
        "type": "greenhouse",
        "board": "chime",
    },
    # Product / SaaS (Greenhouse)
    {"name": "Airbnb", "type": "greenhouse", "board": "airbnb"},
    {"name": "Dropbox", "type": "greenhouse", "board": "dropbox"},
    {"name": "Discord", "type": "greenhouse", "board": "discord"},
    {"name": "Notion", "type": "greenhouse", "board": "notion"},
    {"name": "MongoDB", "type": "greenhouse", "board": "mongodb"},
    {"name": "Databricks", "type": "greenhouse", "board": "databricks"},
    {"name": "Snowflake", "type": "greenhouse", "board": "snowflake"},
    {"name": "Twilio", "type": "greenhouse", "board": "twilio"},
    {"name": "Okta", "type": "greenhouse", "board": "okta"},
    {"name": "HubSpot", "type": "greenhouse", "board": "hubspot"},
    {"name": "Pinterest", "type": "greenhouse", "board": "pinterest"},
    {"name": "Reddit", "type": "greenhouse", "board": "reddit"},
    {"name": "Lyft", "type": "greenhouse", "board": "lyft"},
    {"name": "DoorDash", "type": "greenhouse", "board": "doordash"},
    {"name": "Instacart", "type": "greenhouse", "board": "instacart"},
    {"name": "Block", "type": "greenhouse", "board": "block"},
    {"name": "Plaid", "type": "greenhouse", "board": "plaid"},
    {"name": "Ramp", "type": "greenhouse", "board": "ramp"},
    {"name": "Rippling", "type": "greenhouse", "board": "rippling"},
    {"name": "Gusto", "type": "greenhouse", "board": "gusto"},
    {"name": "Asana", "type": "greenhouse", "board": "asana"},
    {"name": "Airtable", "type": "greenhouse", "board": "airtable"},
    {"name": "Cloudflare", "type": "greenhouse", "board": "cloudflare"},
    {"name": "Datadog", "type": "greenhouse", "board": "datadog"},
    {"name": "HashiCorp", "type": "greenhouse", "board": "hashicorp"},
    {"name": "Elastic", "type": "greenhouse", "board": "elastic"},
    {"name": "Confluent", "type": "greenhouse", "board": "confluent"},
    {"name": "Redis", "type": "greenhouse", "board": "redis"},
    {"name": "Vercel", "type": "greenhouse", "board": "vercel"},
    {"name": "Retool", "type": "greenhouse", "board": "retool"},
    {"name": "Scale AI", "type": "greenhouse", "board": "scaleai"},
    {"name": "Rubrik", "type": "greenhouse", "board": "rubrik"},
    {"name": "CrowdStrike", "type": "greenhouse", "board": "crowdstrike"},
    {"name": "Klaviyo", "type": "greenhouse", "board": "klaviyo"},
    {"name": "Toast", "type": "greenhouse", "board": "toast"},
    {"name": "Duolingo", "type": "greenhouse", "board": "duolingo"},
    {"name": "Roblox", "type": "greenhouse", "board": "roblox"},
    {"name": "Shopify", "type": "greenhouse", "board": "shopify"},
    {"name": "Wayfair", "type": "greenhouse", "board": "wayfair"},
    {"name": "Zillow", "type": "greenhouse", "board": "zillow"},
    {"name": "Uber", "type": "greenhouse", "board": "uber"},
    {"name": "Snap", "type": "greenhouse", "board": "snapchat"},
    {"name": "Roku", "type": "greenhouse", "board": "roku"},
    {"name": "GitLab", "type": "greenhouse", "board": "gitlab"},
    {"name": "Snyk", "type": "greenhouse", "board": "snyk"},
    {"name": "Grafana Labs", "type": "greenhouse", "board": "grafanalabs"},
    {"name": "dbt Labs", "type": "greenhouse", "board": "dbtlabsinc"},
    {"name": "Linear", "type": "greenhouse", "board": "linear"},
    {"name": "Mercury", "type": "greenhouse", "board": "mercury"},
    {"name": "Anduril", "type": "greenhouse", "board": "andurilindustries"},
    {"name": "Palantir", "type": "greenhouse", "board": "palantir"},
    {"name": "SentinelOne", "type": "greenhouse", "board": "sentinelone"},
    {"name": "Zscaler", "type": "greenhouse", "board": "zscaler"},
    {"name": "Monday.com", "type": "greenhouse", "board": "mondaydotcom"},
    {"name": "Epic Games", "type": "greenhouse", "board": "epicgames"},
    {"name": "Riot Games", "type": "greenhouse", "board": "riotgames"},
    {"name": "Grab", "type": "greenhouse", "board": "grab"},
    {"name": "Redfin", "type": "greenhouse", "board": "redfin"},
    {"name": "Rivian", "type": "greenhouse", "board": "rivian"},
    {"name": "Lucid Motors", "type": "greenhouse", "board": "lucidmotors"},
    {"name": "Unity", "type": "greenhouse", "board": "unity"},
    {"name": "OpenAI", "type": "greenhouse", "board": "openai"},
    {"name": "Cohere", "type": "greenhouse", "board": "cohere"},
    {"name": "Hugging Face", "type": "greenhouse", "board": "huggingface"},
    {"name": "Replit", "type": "greenhouse", "board": "replit"},
    {"name": "Supabase", "type": "greenhouse", "board": "supabase"},
    {"name": "Postman", "type": "greenhouse", "board": "postman"},
    {"name": "Canva", "type": "greenhouse", "board": "canva"},
    {"name": "Grammarly", "type": "greenhouse", "board": "grammarly"},
    {"name": "Calendly", "type": "greenhouse", "board": "calendly"},
    {"name": "Webflow", "type": "greenhouse", "board": "webflow"},
    {"name": "Flexport", "type": "greenhouse", "board": "flexport"},
    {"name": "Deel", "type": "greenhouse", "board": "deel"},
    {"name": "Braze", "type": "greenhouse", "board": "braze"},
    {"name": "Amplitude", "type": "greenhouse", "board": "amplitude"},
    {"name": "Mixpanel", "type": "greenhouse", "board": "mixpanel"},
    {"name": "LaunchDarkly", "type": "greenhouse", "board": "launchdarkly"},
    {"name": "PagerDuty", "type": "greenhouse", "board": "pagerduty"},
    {"name": "Fastly", "type": "greenhouse", "board": "fastly"},
    {"name": "Contentful", "type": "greenhouse", "board": "contentful"},
    {"name": "Squarespace", "type": "greenhouse", "board": "squarespace"},
    {"name": "Spotify", "type": "greenhouse", "board": "spotify"},
    {"name": "Kraken", "type": "greenhouse", "board": "kraken"},
    {"name": "SoFi", "type": "greenhouse", "board": "sofi"},
    {"name": "Wise", "type": "greenhouse", "board": "wise"},
    {"name": "Revolut", "type": "greenhouse", "board": "revolut"},
    {"name": "Nubank", "type": "greenhouse", "board": "nubank"},
    {"name": "Gong", "type": "greenhouse", "board": "gong"},
    {"name": "Navan", "type": "greenhouse", "board": "tripactions"},
    {"name": "Weights & Biases", "type": "greenhouse", "board": "wandb"},
    {"name": "Mistral AI", "type": "greenhouse", "board": "mistralai"},
    # Product MNCs (Workday)
    {"name": "Salesforce", "type": "workday", "tenant": "salesforce", "wd_server": "wd12", "site": "External_Career_Site"},
    {"name": "ServiceNow", "type": "workday", "tenant": "servicenow", "wd_server": "wd1", "site": "Careers"},
    {"name": "Intuit", "type": "workday", "tenant": "intuit", "wd_server": "wd1", "site": "Intuit"},
    {"name": "Cisco", "type": "workday", "tenant": "cisco", "wd_server": "wd5", "site": "Cisco_Careers"},
    {"name": "NVIDIA", "type": "workday", "tenant": "nvidia", "wd_server": "wd5", "site": "NVIDIAExternalCareerSite"},
    {"name": "AMD", "type": "workday", "tenant": "amd", "wd_server": "wd1", "site": "External"},
    {"name": "Dell", "type": "workday", "tenant": "dell", "wd_server": "wd1", "site": "External"},
    {"name": "HP", "type": "workday", "tenant": "hp", "wd_server": "wd5", "site": "ExternalCareerSite"},
    {"name": "IBM", "type": "workday", "tenant": "ibm", "wd_server": "wd1", "site": "IBM"},
    {"name": "Oracle", "type": "workday", "tenant": "oracle", "wd_server": "wd1", "site": "Oracle"},
    {"name": "SAP", "type": "workday", "tenant": "sap", "wd_server": "wd3", "site": "SAPCareers"},
    {"name": "Qualcomm", "type": "workday", "tenant": "qualcomm", "wd_server": "wd1", "site": "External"},
    {"name": "Broadcom", "type": "workday", "tenant": "broadcom", "wd_server": "wd1", "site": "External_Career"},
    {"name": "Texas Instruments", "type": "workday", "tenant": "texasinstruments", "wd_server": "wd1", "site": "TI"},
    {"name": "Nike", "type": "workday", "tenant": "nike", "wd_server": "wd1", "site": "nke"},
    # More product / SaaS (Greenhouse)
    {"name": "Perplexity", "type": "greenhouse", "board": "perplexityai"},
    {"name": "Zoom", "type": "greenhouse", "board": "zoom"},
    {"name": "Wix", "type": "greenhouse", "board": "wix"},
    {"name": "Fivetran", "type": "greenhouse", "board": "fivetran"},
    {"name": "Freshworks", "type": "greenhouse", "board": "freshworks"},
    {"name": "Zendesk", "type": "greenhouse", "board": "zendesk"},
    {"name": "Intercom", "type": "greenhouse", "board": "intercom"},
    {"name": "Miro", "type": "greenhouse", "board": "miro"},
    {"name": "Loom", "type": "greenhouse", "board": "loom"},
    {"name": "Benchling", "type": "greenhouse", "board": "benchling"},
    {"name": "Carta", "type": "greenhouse", "board": "carta"},
    {"name": "Checkr", "type": "greenhouse", "board": "checkr"},
    {"name": "Klarna", "type": "greenhouse", "board": "klarna"},
    {"name": "Marqeta", "type": "greenhouse", "board": "marqeta"},
    {"name": "Etsy", "type": "greenhouse", "board": "etsy"},
    {"name": "eBay", "type": "greenhouse", "board": "ebay"},
    {"name": "Expedia", "type": "greenhouse", "board": "expedia"},
    {"name": "Booking.com", "type": "greenhouse", "board": "booking"},
    {"name": "Opendoor", "type": "greenhouse", "board": "opendoor"},
    {"name": "Procore", "type": "greenhouse", "board": "procore"},
    {"name": "Autodesk", "type": "greenhouse", "board": "autodesk"},
    {"name": "New Relic", "type": "greenhouse", "board": "newrelic"},
    {"name": "Dynatrace", "type": "greenhouse", "board": "dynatrace"},
    {"name": "Wiz", "type": "greenhouse", "board": "wizinc"},
    {"name": "JFrog", "type": "greenhouse", "board": "jfrog"},
    {"name": "Sourcegraph", "type": "greenhouse", "board": "sourcegraph"},
    {"name": "Tailscale", "type": "greenhouse", "board": "tailscale"},
    {"name": "1Password", "type": "greenhouse", "board": "1password"},
    {"name": "Docusign", "type": "greenhouse", "board": "docusign"},
    {"name": "Box", "type": "greenhouse", "board": "box"},
    {"name": "Smartsheet", "type": "greenhouse", "board": "smartsheet"},
    {"name": "Productboard", "type": "greenhouse", "board": "productboard"},
    {"name": "Pendo", "type": "greenhouse", "board": "pendo"},
    {"name": "FullStory", "type": "greenhouse", "board": "fullstory"},
    {"name": "Hinge", "type": "greenhouse", "board": "hinge"},
    {"name": "Bumble", "type": "greenhouse", "board": "bumble"},
    {"name": "Waymo", "type": "greenhouse", "board": "waymo"},
    {"name": "SpaceX", "type": "greenhouse", "board": "spacex"},
    {"name": "Tesla", "type": "greenhouse", "board": "tesla"},
    {"name": "Atlassian", "type": "greenhouse", "board": "atlassian"},
    {"name": "GitHub", "type": "greenhouse", "board": "github"},
    {"name": "Runway", "type": "greenhouse", "board": "runwayml"},
    {"name": "Stability AI", "type": "greenhouse", "board": "stabilityai"},
    {"name": "Glean", "type": "greenhouse", "board": "glean"},
    {"name": "Faire", "type": "greenhouse", "board": "fairewholesale"},
    {"name": "Remote", "type": "greenhouse", "board": "remotecom"},
    {"name": "Verkada", "type": "greenhouse", "board": "verkada"},
    {"name": "Samsara", "type": "greenhouse", "board": "samsara"},
    {"name": "Aurora", "type": "greenhouse", "board": "aurora"},
    {"name": "Cruise", "type": "greenhouse", "board": "getcruise"},
    # More product MNCs (Workday)
    {"name": "Amazon", "type": "workday", "tenant": "amazon", "wd_server": "wd5", "site": "Amazon"},
    {"name": "Intel", "type": "workday", "tenant": "intel", "wd_server": "wd1", "site": "External"},
    {"name": "Micron", "type": "workday", "tenant": "micron", "wd_server": "wd1", "site": "External"},
    {"name": "Applied Materials", "type": "workday", "tenant": "amat", "wd_server": "wd1", "site": "External"},
    {"name": "Synopsys", "type": "workday", "tenant": "synopsys", "wd_server": "wd1", "site": "Synopsys_Careers"},
    {"name": "Cadence", "type": "workday", "tenant": "cadence", "wd_server": "wd1", "site": "External_Careers"},
    {"name": "Marvell", "type": "workday", "tenant": "marvell", "wd_server": "wd1", "site": "MarvellCareers"},
    {"name": "Siemens", "type": "workday", "tenant": "siemens", "wd_server": "wd3", "site": "Siemens_Careers"},
    {"name": "Honeywell", "type": "workday", "tenant": "honeywell", "wd_server": "wd5", "site": "Honeywell"},
    {"name": "WellsFargoJobs", "type": "workday", "tenant": "WellsFargoJobs", "wd_server": "wd1", "site": "WellsFargoJobs"},
    {"name": "GE", "type": "workday", "tenant": "ge", "wd_server": "wd5", "site": "GE_External_Site"},
]
